advpn:
  phase1:
    ike_version: 2
    proposal: "des-md5 des-sha1"
    dhgrp: "19 14"
    psksecret: fortinet
    net_device: enable
    mode_cfg: enable
    add_route: disable
    auto_discovery_receiver: enable
    auto_discovery_shortcuts: dependent
    network_overlay: enable

  phase2:
    proposal: "des-md5 des-sha1"
    dhgrp: "19 14"
    auto_negotiate: enable
    keylifeseconds: 43200
    src_subnet: "0.0.0.0 0.0.0.0"
    dst_subnet: "0.0.0.0 0.0.0.0"

  tunnels:
    - name: wan1-vpn1
      branch_wan: wan1
      hub: dallas
      hub_wan: wan1
      network_id: 1

    - name: wan1-vpn2
      branch_wan: wan1
      hub: dallas
      hub_wan: wan2
      network_id: 2

    - name: wan2-vpn3
      branch_wan: wan2
      hub: dallas
      hub_wan: wan1
      network_id: 3

    - name: wan2-vpn4
      branch_wan: wan2
      hub: dallas
      hub_wan: wan2
      network_id: 4

    - name: wan1-vpn5
      branch_wan: wan1
      hub: chicago
      hub_wan: wan1
      network_id: 5

    - name: wan1-vpn6
      branch_wan: wan1
      hub: chicago
      hub_wan: wan2
      network_id: 6

    - name: wan2-vpn7
      branch_wan: wan2
      hub: chicago
      hub_wan: wan1
      network_id: 7

    - name: wan2-vpn8
      branch_wan: wan2
      hub: chicago
      hub_wan: wan2
      network_id: 8

  sdwan:
    branch:
      health_checks:
        - name: dc01
          server: 10.255.0.1
          members: [1, 2, 3, 4]
          packetloss_threshold: 5

        - name: dc02
          server: 10.255.0.2
          members: [5, 6, 7, 8]
          packetloss_threshold: 5

      services:
        - name: DC01
          health_check: dc01
          priority_members: [1, 2, 3, 4]

        - name: DC02
          health_check: dc02
          priority_members: [5, 6, 7, 8]

      inet_service:
        name: inet
        src: rfc1918grp
        dst: rfc1918grp
        dst_negate: enable

    hub:
      inet_service:
        name: Generic_INET
        src: rfc1918grp
        dst: rfc1918grp
        dst_negate: enable

      route_services:
        - name: SDWAN_1
          route_tag: 1
          src: rfc1918grp
          priority_members: [1]

        - name: SDWAN_2
          route_tag: 2
          src: rfc1918grp
          priority_members: [2]

        - name: SDWAN_3
          route_tag: 3
          src: rfc1918grp
          priority_members: [3]

        - name: SDWAN_4
          route_tag: 4
          src: rfc1918grp
          priority_members: [4]

  bgp:
    asn: 65152
    session_mode: per_overlay
    ebgp_multipath: enable
    ibgp_multipath: enable
    additional_path: enable
    recursive_next_hop: enable
    tag_resolve_mode: merge
    graceful_restart: enable
    additional_path_select: 4

    advertisement_interval: 1
    link_down_failover: enable
    soft_reconfiguration: enable
    remote_as: 65152
    keep_alive_timer: 1
    holdtime_timer: 3
    connect_timer: 1
    additional_path_mode: both
    adv_additional_path: 8
    adv_additional_path_branch: 8
    route_reflector_client: enable
    activate6: disable
    capability_graceful_restart6: disable
    next_hop_self: enable
    soft_reconfiguration6: disable

  branch:
    route_maps:
      fail:
        dallas:
          name: VPN-DALLAS-FAIL
          community: "65152:99"
        chicago:
          name: VPN-CHICAGO-FAIL
          community: "65152:99"

  interhub_ipsec:
    ike_version: 2
    peertype: any
    net_device: enable
    proposal: "des-md5 des-sha1"
    add_route: disable
    dpd: on-idle
    npu_offload: disable
    dhgrp: "19 14"
    psksecret: fortinet
    dpd_retryinterval: 60
