site_name: dallas, tx
site_slug: dallas
fgt_hostname: Hub01

lan:
  interface: port10
  ip: 10.101.1.1 255.255.255.0
  subnet: 10.101.1.0 255.255.255.0
  dhcp_start: 10.101.1.100
  dhcp_end: 10.101.1.199

lo_hc:
  interface: lo.hc
  ip: 10.250.1.1 255.255.255.255

lo_bgp:
  interface: lo.bgp
  ip: 10.250.0.1 255.255.255.255

wan:
  wan1:
    interface: port1
    ip: 100.64.0.10 255.255.255.0
  wan2:
    interface: port2
    ip: 100.65.0.10 255.255.255.0

hub_overlay_interfaces:
  - name: hub1-wan1-vpn1
    member_id: 1
    underlay_wan: wan1
    network_id: 1
    overlay_subnet: 10.250.1.0 255.255.255.0

  - name: hub1-wan2-vpn2
    member_id: 3
    underlay_wan: wan2
    network_id: 2
    overlay_subnet: 10.250.2.0 255.255.255.0

  - name: hub1-wan1-vpn3
    member_id: 2
    underlay_wan: wan1
    network_id: 3
    overlay_subnet: 10.250.3.0 255.255.255.0

  - name: hub1-wan2-vpn4
    member_id: 4
    underlay_wan: wan2
    network_id: 4
    overlay_subnet: 10.250.4.0 255.255.255.0

interhub:
  tunnel_name: dallas-chicago
  phase2_name: dallas-chicago-p2
  policy_name: dallas-chicago-link
  parent_interface: port10
  localid: dallas
  remote_gw: 100.64.0.20
  tunnel_ip: 10.254.254.1 255.255.255.255
  remote_tunnel_ip: 10.254.254.2 255.255.255.255
