site_name: phoenix, az
site_slug: phoenix
fgt_hostname: Branch01

lan:
  interface: port1
  ip: 10.120.1.1 255.255.255.0
  subnet: 10.120.1.0 255.255.255.0
  dhcp_start: 10.120.1.100
  dhcp_end: 10.120.1.199

lo_hc:
  interface: lo.hc
  ip: 10.255.0.11 255.255.255.255

wan:
  wan1:
    interface: port10
  wan2:
    interface: port9
